name: Selenium Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted  # Specify that it should run on your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver
          echo "/usr/lib/chromium-browser/chromium-browser" >> $GITHUB_PATH
          echo "/usr/lib/chromium-browser/chromedriver" >> $GITHUB_PATH

      - name: Run Selenium tests
        run: |
          pytest --html=reports/test_report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test_report.html
